language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
   - "if [[ $DJANGO == 'dev' ]]; then pip install git+https://github.com/django/django.git#egg=Django; else pip install Django==$DJANGO; fi"
   - pip install -r requirements.txt
   - python setup.py develop
env:
  - DJANGO="1.8.9"
  - DJANGO="1.9.2"
  - DJANGO="dev"
script: python setup.py nosetests
